// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv`

interface CloudflareEnv {
	ACCESS_TEAM_DOMAIN: "";
	ACCESS_AUD: "";
	PRODUCT_IMAGES: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
